import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "./graphQL/apollo-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Curator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}> 
        <ApolloWrapper>
          {children}
        </ApolloWrapper> 
       </body>
    </html>
  );
}
